# Generated by Django 2.2.16 on 2022-01-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211102_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Заголовок группы'},
        ),
    ]
