# Generated by Django 2.2.16 on 2022-01-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_added',
            new_name='pub_date',
        ),
    ]
